### ISSUE TITLE
Lineage doesn't work yet

### ISSUE THREAD

**Issue by geoffp** [pattern-lab/patternengine-node-underscore#1]
I am using Pattern Lab Node `v2.3` on `Mac`, using the `gulp` configuration.
##### Expected Behavior

Lineage hunting should work.
##### Actual Behavior

It doesn't.
##### Steps to Reproduce

Call one pattern from another, go to the called pattern, see how the patterns the use it are not listed in the pattern info box.

**Comment by bmuenzenmeyer** [comment]
Is this still active?

**Comment by geoffp** [comment]
Nope! Closing this.
